title: John Hayes-Reed (aka Johnny Rubeard)
description: > # this means to ignore newlines until "baseurl:"
  The musings of myself. A diary of my findings on my journey through software development.
  A record of what I have picked up, written in a simple way that makes sense to me, how I would
  wish to have seen it written. Hopefully in a way that is useful to you too!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: johnny_rubeard #if your site has a twitter account, enter it here

# Author Settings
author: John Hayes-Reed # add your name
author-img: david-freeman.jpg # add your photo
about-author: >
  Technical Design Authority.
  Software Engineer.
  Agile Enthusiast.
  Rubyist.
  But most of all,
  a Husband and Father.
social-twitter: johnny_rubeard # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: John-Hayes-Reed # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: john.hayes.reed@rubeard.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "vendor"]
